name       : biber
version    : '2.6'
release    : 4
source     :
    - https://github.com/plk/biber/archive/v2.6.tar.gz : 77bea9a1bbd319ff776bd6ad1f24a245ca8f102e519fb4db527e4b28dfaf1a95
license    : Artistic-2.0
component  : office
summary    : A backend bibliography processor for biblatex
description: |
    A backend bibliography processor for biblatex
builddeps  :
    - perl-module-build
rundeps    :
    - log4perl
    - perl-autovivification
    - perl-class-accessor
    - perl-data-compare
    - perl-data-dump
    - perl-data-uniqid
    - perl-date-simple
    - perl-file-slurp
    - perl-list-allutils
    - perl-ipc-run3
    - perl-regexp-common
    - perl-text-bibtex
    - perl-text-roman
    - perl-unicode-linebreak
    - perl-uri
    - perl-xml-libxml-simple
    - texlive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
