name       : biber
version    : '2.11'
release    : 17
source     :
    - https://github.com/plk/biber/archive/v2.11.tar.gz : 4839cc5b73cf4d960ef751636f2d29df7212c722ddb5073885df404b785f0cd2
homepage   : https://github.com/plk/biber
license    : Artistic-2.0
component  : office
summary    : A backend bibliography processor for biblatex
description: |
    Biber is a sophisticated bibliography processing backend for the LaTeX biblatex package. It supports an unsurpassed feature set for automated conformance to complex bibliography style requirements such as labelling, sorting and name handling. It has comprehensive Unicode support
builddeps  :
    - libwww-perl
    - log4perl
    - perl-autovivification
    - perl-business-isbn
    - perl-business-ismn
    - perl-business-issn
    - perl-class-accessor
    - perl-class-factory-util
    - perl-class-singleton
    - perl-clone
    - perl-config-autoconf
    - perl-data-compare
    - perl-data-uniqid
    - perl-datetime-calendar-julian
    - perl-datetime-format-builder
    - perl-datetime-format-strptime
    - perl-encode-eucjpascii
    - perl-encode-hanextra
    - perl-encode-jis2k
    - perl-eval-closure
    - perl-exception-class
    - perl-extutils-libbuilder
    - perl-file-which
    - perl-io-utf8-strict
    - perl-ipc-run3
    - perl-lingua-translit
    - perl-list-allutils
    - perl-list-moreutils
    - perl-module-build
    - perl-mozilla-ca
    - perl-mro-compat
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-params-util
    - perl-params-validate
    - perl-parse-recdescent
    - perl-regexp-common
    - perl-role-tiny
    - perl-sort-key
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-test-differences
    - perl-text-bibtex
    - perl-text-csv
    - perl-text-csv-xs
    - perl-text-roman
    - perl-unicode-collate
    - perl-unicode-linebreak
    - perl-xml-libxml-simple
    - perl-xml-libxslt
    - perl-xml-writer
rundeps    :
    - libwww-perl
    - log4perl
    - perl-autovivification
    - perl-business-isbn
    - perl-business-ismn
    - perl-business-issn
    - perl-class-accessor
    - perl-class-factory-util
    - perl-class-singleton
    - perl-clone
    - perl-data-compare
    - perl-data-uniqid
    - perl-datetime-calendar-julian
    - perl-datetime-format-builder
    - perl-datetime-format-strptime
    - perl-encode-eucjpascii
    - perl-encode-hanextra
    - perl-encode-jis2k
    - perl-eval-closure
    - perl-exception-class
    - perl-file-slurper
    - perl-io-utf8-strict
    - perl-ipc-run3
    - perl-lingua-translit
    - perl-list-allutils
    - perl-list-moreutils
    - perl-mozilla-ca
    - perl-mro-compat
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-params-util
    - perl-params-validate
    - perl-parse-recdescent
    - perl-regexp-common
    - perl-role-tiny
    - perl-sort-key
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-text-bibtex
    - perl-text-csv
    - perl-text-csv-xs
    - perl-text-roman
    - perl-unicode-collate
    - perl-unicode-linebreak
    - perl-xml-libxml-simple
    - perl-xml-libxslt
    - perl-xml-writer
    - texlive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
#check      : |
#    %perl_build test
