name       : biber
version    : '2.5'
release    : 10
source     :
    - https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.5/biblatex-biber.tar.gz/download : c6a0c3ee369d7e9c7d59b4be1d0a3ecfa3e32a391bc97e7a5e6a3a932e4209c8
license    : Artistic-2.0
component  : office
summary    : A backend bibliography processor for biblatex
description: |
    A backend bibliography processor for biblatex
builddeps  :
    - perl-config-autoconf
    - perl-extutils-libbuilder
    - perl-file-which
    - perl-module-build
    - perl-test-differences
    - log4perl
    - perl-autovivification
    - perl-b-hooks-endofscope
    - perl-business-isbn
    - perl-business-ismn
    - perl-business-issn
    - perl-class-accessor
    - perl-class-data-inheritable
    - perl-class-factory-util
    - perl-class-inspector
    - perl-class-singleton
    - perl-data-compare
    - perl-data-dump
    - perl-date-simple
    - perl-data-uniqid
    - perl-datetime
    - perl-datetime-calendar-julian
    - perl-datetime-format-builder
    - perl-datetime-format-strptime
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-encode-eucjpascii
    - perl-encode-hanextra
    - perl-encode-jis2k
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-file-slurp
    - perl-ipc-run3
    - perl-lingua-translit
    - perl-list-allutils
    - perl-list-moreutils
    - perl-list-moreutils-xs
    - perl-lwp-protocol-https
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-package-stash
    - perl-params-util
    - perl-params-validate
    - perl-params-validationcompiler
    - perl-regexp-common
    - perl-role-tiny
    - perl-sort-key
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-text-bibtex
    - perl-text-csv
    - perl-text-roman
    - perl-unicode-linebreak
    - perl-uri
    - perl-variable-magic
    - perl-xml-libxml-simple
    - perl-xml-libxslt
    - perl-xml-writer
rundeps    :
    - log4perl
    - perl-autovivification
    - perl-b-hooks-endofscope
    - perl-business-isbn
    - perl-business-ismn
    - perl-business-issn
    - perl-class-accessor
    - perl-class-data-inheritable
    - perl-class-factory-util
    - perl-class-inspector
    - perl-class-singleton
    - perl-data-compare
    - perl-data-dump
    - perl-date-simple
    - perl-data-uniqid
    - perl-datetime
    - perl-datetime-calendar-julian
    - perl-datetime-format-builder
    - perl-datetime-format-strptime
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-encode-eucjpascii
    - perl-encode-hanextra
    - perl-encode-jis2k
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-file-slurp
    - perl-ipc-run3
    - perl-lingua-translit
    - perl-list-allutils
    - perl-list-moreutils
    - perl-list-moreutils-xs
    - perl-lwp-protocol-https
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-package-stash
    - perl-params-util
    - perl-params-validate
    - perl-params-validationcompiler
    - perl-regexp-common
    - perl-role-tiny
    - perl-sort-key
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-text-bibtex
    - perl-text-csv
    - perl-text-roman
    - perl-unicode-linebreak
    - perl-uri
    - perl-variable-magic
    - perl-xml-libxml-simple
    - perl-xml-libxslt
    - perl-xml-writer
    - texlive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
