name       : biber
version    : '2.7'
release    : 2
source     :
    - https://github.com/plk/biber/archive/v2.7.tar.gz : a0afc4cd97d56f4f433e476de1d4bd9bf9740eb29191bf616b1ea3f424408d9f
license    : Artistic-2.0
component  : office
summary    : A backend bibliography processor for biblatex
description: |
    A backend bibliography processor for biblatex
builddeps  :
    - perl-module-build
rundeps    :
    - log4perl
    - perl-autovivification
    - perl-class-accessor
    - perl-data-compare
    - perl-data-dump
    - perl-data-uniqid
    - perl-date-simple
    - perl-file-slurp
    - perl-list-allutils
    - perl-ipc-run3
    - perl-regexp-common
    - perl-text-bibtex
    - perl-text-roman
    - perl-unicode-linebreak
    - perl-uri
    - perl-xml-libxml-simple
    - texlive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
