name       : biber
version    : '2.6'
release    : 6
source     :
    - https://github.com/plk/biber/archive/v2.6.tar.gz : 77bea9a1bbd319ff776bd6ad1f24a245ca8f102e519fb4db527e4b28dfaf1a95
license    : Artistic-2.0
component  : office
summary    : A backend bibliography processor for biblatex
description: |
    A backend bibliography processor for biblatex
builddeps  :
    - perl-module-build
rundeps    :
    - log4perl
    - perl-autovivification
    - perl-b-hooks-endofscope
    - perl-class-accessor
    - perl-class-data-inheritable
    - perl-class-factory-util
    - perl-class-inspector
    - perl-class-singleton
    - perl-data-compare
    - perl-data-dump
    - perl-data-uniqid
    - perl-date-simple
    - perl-datetime
    - perl-datetime-format-builder
    - perl-datetime-locale
    - perl-datetime-calendar-julian
    - perl-datetime-format-strptime
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-file-slurp
    - perl-ipc-run3
    - perl-list-allutils
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validate
    - perl-regexp-common
    - perl-role-tiny
    - perl-variable-magic
    - perl-package-deprecationmanager
    - perl-params-util
    - perl-params-validationcompiler
    - perl-sort-key
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-install
    - perl-sub-identify
    - perl-sub-name
    - perl-text-bibtex
    - perl-text-csv
    - perl-text-roman
    - perl-unicode-linebreak
    - perl-uri
    - perl-variable-magic
    - perl-xml-libxml-simple
    - texlive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
